### ISSUE TITLE
Error no such directory using custom destination

### ISSUE THREAD

**Issue by softdays** [jnwltr/swagger-angular-generator#47]
Error: ENOENT: no such file or directory, mkdir 'D:\dev\projects\...\src\app\api\defs
When I try to execute the command below:
swagger-angular-generator -s src/swagger.json -d src/app/api --no-store

OS Windows 10 - Node  8.9.4 - Npm 5.6.0

**Comment by softdays** [comment]
If I created it before executing the command everything is ok

**Comment by softdays** [comment]
Would it not be nice if the tool remove/create the destination directory for us?

**Comment by jnwltr** [comment]
Creation yes, deletion not sure. What if you had sth important there.

**Comment by softdays** [comment]
Yes you're right. So it's better to let the user handle that stuff.
