### ISSUE TITLE
Dashed query param causes typescript error

### ISSUE THREAD

**Issue by softdays** [jnwltr/swagger-angular-generator#49]
If the query param contains a dash, it causes a typescript error:

![compile_error](https://user-images.githubusercontent.com/948293/43308701-ab53706a-9182-11e8-8cf6-181a2c3867bc.png)

**Comment by jnwltr** [comment]
And is it smart to have dashes there? How should that behave? I think the
best solution would be to avoid these in the api, since the usage
implication might not be worth.

**Comment by softdays** [comment]
That's not the point here. Dashs are allowed characters in query strings. My point of view is that the tool must not impose too many choices.

**Comment by jnwltr** [comment]
Not sure what do you propose. Could you be more informative, please? Or
make a PR if you suggest some specific modification. Thx

**Comment by softdays** [comment]
Just add quotes on generated variables:

![proposal](https://user-images.githubusercontent.com/948293/43346689-749d4454-91f2-11e8-9c78-8366bc3ccaa8.png)

**Comment by jnwltr** [comment]
And do you think we should support non-alphanumeric symbols in the query params? I do understand they are legitimate, but would like to keep simplicity of both API and generator code itself. I am not quite sure this way of param naming is reasonable.

What programming language do you generate the schema from, btw?

**Comment by jnwltr** [comment]
Which is what, being ready for dashes? It is imo very specific (do you
really need them on your BE, btw?).
But ok, you are welcome to make a PR. But, please, do not forget to respect
linter settings.

**Comment by softdays** [comment]
Despite I very like your tool because it integrates very well in our frontend environment I finally decided to give a try with [openapi-generator](https://github.com/OpenAPITools/openapi-generator) which already provides support for dash-case query parameters and basePath InjectionToken (another thing I need)

**Comment by jnwltr** [comment]
Sure, np.

**Comment by jnwltr** [comment]
Btw, dashed params should be solved as a by-product of https://github.com/jnwltr/swagger-angular-generator/pull/71/files.
