### ISSUE TITLE
Angular 6 compatibility

### ISSUE THREAD

**Issue by jcctudela** [jnwltr/swagger-angular-generator#56]
Is it in the road map supporting Angular 6?

I've seen that the RXJS has change in Angular6 imports

**Comment by jnwltr** [comment]
Yes, definitely. We are waiting for a proper moment. What do you think?

We are using rxjs-compat (`npm i rxjs-compat --save-dev`) in projects w/
ng6 for the backward compatibility purposes.

**Comment by jcctudela** [comment]
Great! I've make few changes in my local copy of the code to avoid using 'rxjs-compat' and it works in my case, but I'm sure that the change for angular 6 compatibility must be bigger than a few changes

**Comment by jnwltr** [comment]
I am not sure I understand, anyway if you have an opinion of the date to make the breaking change (upgrade to Angular 6), let us know.
