### ISSUE TITLE
Actions.Error payload should be HttpErrorResponse or HttpErrorResponse.error property.

### ISSUE THREAD

**Issue by soundTricker** [jnwltr/swagger-angular-generator#60]
Currently, `Error` action payload is set from message property of `HttpErrorResponse`.

https://github.com/jnwltr/swagger-angular-generator/blob/master/demo-app/client/generated/store/login/login/states/effects.ts#L25

But `HttpErrorResponse.message` is created in angular framework. so it is not user friendly message and it is not created by backend.

https://github.com/angular/angular/blob/317d40d879cc5eac1073a9182384423596fc098b/packages/common/http/src/response.ts#L325

I guess `Error` action's payload  should be `HttpErrorResponse` or `HttpErrorResponse.error`.

**Comment by fazpu** [comment]
I agree. Thank you for the issue. Please, let's make it `HttpErrorResponse`. I believe we should pass the entire object in case you wanted to have conditions based on the error status.
