### ISSUE TITLE
Prefer OperationId over url segment for method naming

### ISSUE THREAD

**Issue by chwiede** [jnwltr/swagger-angular-generator#69]
Hi,

would it be possible to prefer given operation-id instead of last part of url?

Here's an example:

I've got following `swagger.json`:

```json
{
  "swagger": "2.0",
  "info": { "version": "v1", "title": "My Api" },
  "paths": {
    "/api/Project/{id}": {
      "delete": {
        "tags": ["Project", "Delete"],

        "summary": "Deletes a project",
        "operationId": "DeleteProject",
        "consumes": [],
        "produces": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique id of a project",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": { "description": "Success" },
          "404": { "description": "Not Found" }
        }
      }
    }
  },
  "definitions": {}
}
```

However, this produces following controller:

```typescript
@Injectable()
export class ProjectService {
  constructor(private http: HttpClient) {}

  /**
   * Deletes a project
   * http://undefined/swagger/swagger-ui.html#!/Project/DeleteProject
   */
  project(params: ProjectParams): Observable<void> {
    const pathParams = {
      id: params.id,
    };
    return this.http.delete<void>(`/api/Project/${pathParams.id}`);
  }
}
```

I don't get why the method is named just 'project'. Well, it's the last part of the url, but there's no chance to see that's a delete-method when using the generated controller.

Is it possible to name the method just as defined in `operationId`?

Thank's in advance for any hint.

**Comment by jnwltr** [comment]
OperationId is used as a fallback if there would be multiple methods of the
same name (from last section of URL as you are pointing out).
I did it for the sake of naming simplicity. We are using it on several
projects and it works pretty well, you'll get used to it.

I can imagine, we would hide naming strategy (use operationId always)
behind params, still not sure it's worth.

In fact you do not need to know what http method is used, you call it, see
the description (docs) in your IDE, plus can always check the detail of the
method via checking the source code, visiting swagger UI, etc. And do not
forget operationId does not necessarily need to contain the http method
used, unless it maybe usually does.

**Comment by chwiede** [comment]
Thank's for the feedback. Is there maybe a possibility (config, etc) to use operationId as primary source for the generated method name?

If not, I'll solve it with documentation.

**Comment by jnwltr** [comment]
If you really needed _use operationId always_, feel free to make a PR with this strategy behind command line option (backward compatible so default is the current solution). It should not be very hard.

Thanks.
