### ISSUE TITLE
What's changed in v4?

### ISSUE THREAD

**Issue by yluijten** [jnwltr/swagger-angular-generator#90]
Is it possible to add a CHANGELOG.md to the repository and list which changes are implemented? Now it's unclear what changed in version 4 compared to version 3.

**Comment by jnwltr** [comment]
Functionally, its an upgrade of npm packages (mainly to Angular 7).
You can always check the list of commits, e.g. here https://github.com/jnwltr/swagger-angular-generator/compare/v3.0.0...master.

I'll add a changelog generator next time (unless you do it yourself, you are welcome to make a PR).
