### ISSUE TITLE
Generating with the --no-store option doesn't work

### ISSUE THREAD

**Issue by raphael-jungers** [jnwltr/swagger-angular-generator#91]
Hello,

It seems that generating code with the --no-store option is still generating the common/utils.ts file, but not the formArrayExtended.ts and formMap.ts files.

I don't think the utils.ts file should be generated if the --no-store option was used ?

I'm using version 4.0.0 of the library.

Thanks

**Comment by jnwltr** [comment]
Please, check this one https://github.com/jnwltr/swagger-angular-generator/pull/107/commits/a137dde5b952657b8619d77808ae5010fb90c3b8. If you wanted to make a version w/o forms, be welcome to make a PR with additional option.
